import React, { useEffect, useMemo, useState } from 'react'
import { Download, FileSpreadsheet, RefreshCw, Search, Upload, SlidersHorizontal } from 'lucide-react'
import { api, apiUpload, downloadFile } from '../api'
import { Badge, Button, Card, CardHeader, Empty, ErrorBanner, PageHeader } from '../components/Common'
import { FLAGS, compactMoney, pct, marketName } from '../utils'
import { PortfolioAiRecoveryAction } from '../components/AiRecovery'
import { useI18n } from '../i18n.jsx'

function statusTone(status){return status==='READY_FOR_DECISION'?'success':status==='CONDITIONAL'?'warning':'neutral'}

export default function Portfolio({projects,markets=[],onReload,onOpen}){
  const { locale, t } = useI18n()
  const [file,setFile]=useState(null);const[loading,setLoading]=useState(false);const[result,setResult]=useState(null);const[error,setError]=useState('')
  const [matrix,setMatrix]=useState(null);const[matrixLoading,setMatrixLoading]=useState(false);const[query,setQuery]=useState('')
  const [optOps,setOptOps]=useState([]);const[optLoading,setOptLoading]=useState(false);const[optResult,setOptResult]=useState(null)
  const [budget,setBudget]=useState(3000000);const[objective,setObjective]=useState('robust_profit');const[gamma,setGamma]=useState(2)
  const [marketCap,setMarketCap]=useState(30);const[productCap,setProductCap]=useState(40);const[highRiskCap,setHighRiskCap]=useState(20);const[minMarkets,setMinMarkets]=useState(2);const[reserve,setReserve]=useState(10)
  const batches=useMemo(()=>{const m={};for(const p of projects){const b=p.attributes?.portfolio_batch_id;if(!b)continue;(m[b] ||= []).push(p)}return m},[projects])
  async function upload(){if(!file)return;setLoading(true);setError('');try{const fd=new FormData();fd.append('file',file);const r=await apiUpload('/api/portfolio/import',fd);setResult(r);await onReload();await loadMatrix()}catch(e){setError(e.message)}finally{setLoading(false)}}
  async function loadMatrix(){setMatrixLoading(true);try{setMatrix(await api('/api/portfolio/matrix'))}catch(e){setError(e.message)}finally{setMatrixLoading(false)}}
  async function loadOptimizationInputs(){try{const r=await api('/api/portfolio/optimization-inputs');setOptOps((r.opportunities||[]).map(x=>({...x,enabled:x.enabled!==false,mandatory:false,prohibited:false})));setOptResult(null)}catch(e){setError(e.message)}}
  useEffect(()=>{loadMatrix();loadOptimizationInputs()},[projects.length])
  const matrixRows=useMemo(()=>{const q=query.trim().toLowerCase();return (matrix?.rows||[]).filter(r=>!q||String(r.sku||'').toLowerCase().includes(q)||String(r.title||'').toLowerCase().includes(q)||String(r.hs_code||'').toLowerCase().includes(q))},[matrix,query])
  function updateOp(idx,patch){setOptOps(x=>x.map((o,i)=>i===idx?{...o,...patch}:o));setOptResult(null)}
  async function optimize(){setOptLoading(true);setError('');try{const r=await api('/api/portfolio/optimize',{method:'POST',body:JSON.stringify({total_budget:Number(budget),objective,gamma:Number(gamma),market_cap_ratio:Number(marketCap)/100,product_cap_ratio:Number(productCap)/100,high_risk_cap_ratio:Number(highRiskCap)/100,high_risk_threshold:.65,min_markets:Number(minMarkets),min_allocation:Math.max(1,Number(budget)*.01),reserve_ratio:Number(reserve)/100,opportunities:optOps})});setOptResult(r)}catch(e){setError(e.message)}finally{setOptLoading(false)}}
  return <div className="page-stack"><PageHeader title={t('portfolioTitle')} actions={<><PortfolioAiRecoveryAction onComplete={async()=>{await onReload?.();await loadMatrix()}}/><Button icon={RefreshCw} loading={matrixLoading} onClick={loadMatrix}>{locale==='zh'?'刷新矩阵':'Refresh matrix'}</Button><Button icon={Download} variant="secondary" onClick={()=>downloadFile('/api/portfolio/template.csv','GoGlobal Intelligence_portfolio_template.csv')}>{locale==='zh'?'模板':'Template'}</Button></>}/><ErrorBanner error={error}/>
    <Card><CardHeader title={t('importSku')}/><div className="portfolio-upload"><label className="file-drop"><FileSpreadsheet size={24}/><div><b>{file?.name||t('chooseFile')}</b></div><input type="file" accept=".csv,.xlsx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button icon={Upload} variant="primary" loading={loading} disabled={!file} onClick={upload}>{t('importDrafts')}</Button></div>{result&&<div className="import-result"><Badge tone="success">{result.created_count} {t('created')}</Badge><Badge tone={result.rejected_count?'warning':'neutral'}>{result.rejected_count} {t('rejected')}</Badge><span>{t('batch')} {result.batch_id}</span>{result.rejected?.length>0&&<div className="rejected-list">{result.rejected.map(r=><div key={r.row_number}><b>{t('row')} {r.row_number}</b><span>{r.errors.join(' · ')}</span></div>)}</div>}</div>}</Card>

    <Card><CardHeader title={t('portfolioMatrix')} meta={matrix?`${matrixRows.length}/${matrix.count} · ${matrix.markets.length} ${locale==='zh'?'市场':'markets'}`:(locale==='zh'?'加载中':'Loading')} actions={matrix?.rows?.length?<div className="table-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)}/></div>:null} />
      {matrixRows.length ? <div className="portfolio-matrix-wrap"><table className="portfolio-matrix"><thead><tr><th>{locale==='zh'?'商品':'Product'}</th><th>HS</th>{matrix.markets.map(m=><th key={m}>{FLAGS[m]||''} {marketName(markets,m,locale,m)}</th>)}</tr></thead><tbody>{matrixRows.map(r=><tr key={r.project_id}><td><button className="portfolio-link" onClick={()=>onOpen(r.project_id)}><b>{r.sku||r.title}</b><span>{r.sku?r.title:r.origin||''}</span></button></td><td>{r.hs_code||t('pending')}</td>{matrix.markets.map(m=>{const c=r.cells?.[m];return <td key={m}>{c?<div className="matrix-cell"><Badge tone={statusTone(c.status)}>{locale==='zh'?({'READY_FOR_DECISION':'可进入决策','CONDITIONAL':'有条件','INSUFFICIENT_EVIDENCE':'证据不足','PENDING':'待处理'}[c.status||'PENDING']||'待处理'):(c.status||'PENDING').replaceAll('_',' ')}</Badge><span>{locale==='zh'?'证据完整度':'Evidence'} {pct(c.evidence_ratio,0)}</span>{c.imports!=null&&<small>{compactMoney(c.imports,'USD')}</small>}</div>:<span className="muted-cell">{locale==='zh'?'未选择':'Not selected'}</span>}</td>})}</tr>)}</tbody></table></div> : <Empty title={t('noMatrix')} />}
    </Card>

    <Card className="portfolio-optimizer"><CardHeader title={locale==='zh'?'产品 × 市场资源配置优化':'Product × market resource allocation'} meta={optOps.length?`${optOps.length} ${locale==='zh'?'个可优化组合':'optimization-ready combinations'}`:null} actions={<><Button variant="secondary" icon={RefreshCw} onClick={loadOptimizationInputs}>{locale==='zh'?'刷新输入':'Refresh inputs'}</Button><Button variant="primary" icon={SlidersHorizontal} loading={optLoading} disabled={!optOps.length} onClick={optimize}>{locale==='zh'?'求解最优配置':'Optimize allocation'}</Button></>}/>
      <div className="optimizer-controls"><label><span>{locale==='zh'?'总预算':'Total budget'}</span><input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value)||0)}/></label><label><span>{locale==='zh'?'目标':'Objective'}</span><select value={objective} onChange={e=>setObjective(e.target.value)}><option value="robust_profit">{locale==='zh'?'鲁棒利润':'Robust profit'}</option><option value="nominal_profit">{locale==='zh'?'名义利润':'Nominal profit'}</option><option value="revenue">{locale==='zh'?'收入':'Revenue'}</option></select></label><label><span>Γ</span><input type="number" step="0.5" min="0" value={gamma} onChange={e=>setGamma(Number(e.target.value)||0)}/></label><label><span>{locale==='zh'?'至少市场数':'Min markets'}</span><input type="number" min="1" value={minMarkets} onChange={e=>setMinMarkets(Number(e.target.value)||1)}/></label><label><span>{locale==='zh'?'单市场上限 %':'Market cap %'}</span><input type="number" value={marketCap} onChange={e=>setMarketCap(Number(e.target.value)||0)}/></label><label><span>{locale==='zh'?'单产品上限 %':'Product cap %'}</span><input type="number" value={productCap} onChange={e=>setProductCap(Number(e.target.value)||0)}/></label><label><span>{locale==='zh'?'高风险上限 %':'High-risk cap %'}</span><input type="number" value={highRiskCap} onChange={e=>setHighRiskCap(Number(e.target.value)||0)}/></label><label><span>{locale==='zh'?'预算保留 %':'Reserve %'}</span><input type="number" value={reserve} onChange={e=>setReserve(Number(e.target.value)||0)}/></label></div>
      {optOps.length?<div className="optimization-input-table"><div className="optimization-input-head"><span></span><span>{locale==='zh'?'产品 × 市场':'Product × market'}</span><span>{locale==='zh'?'市场毛利':'Market margin'}</span><span>{locale==='zh'?'风险':'Risk'}</span><span>{locale==='zh'?'不确定度':'Uncertainty'}</span><span>{locale==='zh'?'规则':'Rule'}</span></div>{optOps.map((o,i)=><div className="optimization-input-row" key={`${o.project_id}-${o.market}`}><span><input type="checkbox" checked={o.enabled&&!o.prohibited} onChange={e=>updateOp(i,{enabled:e.target.checked,prohibited:!e.target.checked?o.prohibited:false})}/></span><b>{o.product} · {FLAGS[o.market]||''} {marketName(markets,o.market,locale,o.market)}</b><span>{pct(o.margin_at_market_price)}</span><span>{pct(o.risk_score)}</span><span>{pct(o.uncertainty)}</span><select value={o.prohibited?'exclude':o.mandatory?'must':'normal'} onChange={e=>updateOp(i,{mandatory:e.target.value==='must',prohibited:e.target.value==='exclude',enabled:e.target.value!=='exclude'})}><option value="normal">{locale==='zh'?'正常':'Normal'}</option><option value="must">{locale==='zh'?'必须进入':'Must enter'}</option><option value="exclude">{locale==='zh'?'禁止进入':'Exclude'}</option></select></div>)}</div>:<Empty title={locale==='zh'?'需要至少一个具备市场价格与成本数据的产品市场组合':'Need at least one product-market pair with market price and cost evidence'}/>}
      {optResult?<><div className="metric-grid optimizer-kpis"><div><span>{locale==='zh'?'预算使用':'Budget used'}</span><b>{compactMoney(optResult.budget_used)}</b></div><div><span>{locale==='zh'?'名义利润':'Nominal profit'}</span><b>{compactMoney(optResult.nominal_profit)}</b></div><div><span>{locale==='zh'?'鲁棒利润下界':'Robust profit lower bound'}</span><b>{compactMoney(optResult.robust_profit_lower_bound)}</b></div><div><span>{locale==='zh'?'加权风险':'Weighted risk'}</span><b>{pct(optResult.weighted_risk)}</b></div><div><span>{locale==='zh'?'保留预算':'Reserve'}</span><b>{compactMoney(optResult.reserve)}</b></div></div><div className="allocation-list">{(optResult.allocations||[]).map(a=><div key={`${a.product_id}-${a.market}`}><div><b>{a.product}</b><span>{FLAGS[a.market]||''} {marketName(markets,a.market,locale,a.market)}</span></div><strong>{compactMoney(a.allocation)}</strong><span>{locale==='zh'?'预计利润':'Expected profit'} {compactMoney(a.nominal_profit)}</span></div>)}</div></>:null}
    </Card>

    <Card><CardHeader title={t('portfolioBatches')} meta={locale==='zh'?`${Object.keys(batches).length} 个导入批次`:`${Object.keys(batches).length} imported batch(es)`}/>{Object.keys(batches).length?<div className="portfolio-batches">{Object.entries(batches).map(([batch,items])=><div className="portfolio-batch" key={batch}><div className="portfolio-batch-head"><b>{batch}</b><span>{items.length} {locale==='zh'?'个 SKU':'SKU'}</span></div><div className="portfolio-items">{items.map(p=><button key={p.id} onClick={()=>onOpen(p.id)}><div><b>{p.attributes?.portfolio_sku||p.title}</b><span>{p.title}</span></div><small>{p.hs_code?`HS ${p.hs_code}`:locale==='zh'?'HS 待确认':'HS pending'} · {p.markets?.length||0} {locale==='zh'?'个市场':'markets'}</small></button>)}</div></div>)}</div>:<Empty title={t('noPortfolio')} />}</Card>
  </div>
}
