import React, { createContext, useContext, useMemo, useState } from 'react'

const DICT = {
  zh: {
    workspace:'工作台', setup:'项目设置', scan:'市场扫描', explorer:'机会探索', trade:'贸易结构', tariffSupply:'关税与供应', ebay:'eBay 研究', cost:'成本与利润', decision:'决策案例', portfolio:'产品组合', backbone:'数据底座', sources:'数据源',
    newOpen:'新建 / 打开商品', exportExcel:'导出 Excel', noProject:'暂无项目', active:'进行中', draft:'草稿', local:'本地',
    workspaceTitle:'工作台', workspaceSub:'', projects:'项目', filterProjects:'筛选项目',
    newAnalysis:'新建分析', whatProduct:'商品', chooseCategory:'选择最接近的商品分类', addAttributes:'补充关键属性', product:'商品', continue:'继续', back:'返回', createAnalysis:'创建分析', skipDetails:'跳过详情', browseCategories:'浏览 eBay 分类', createDraft:'创建草稿',
    targetMarkets:'目标市场', selected:'已选择', searchCountry:'搜索国家或地区', allRegions:'全部地区', featured:'重点市场', tradeOnly:'贸易研究', fullSupport:'完整决策支持', selectAllRegion:'选择本洲', clear:'清除', globalMap:'全球市场地图', regionList:'按洲选择', mapHint:'',
    northAmerica:'北美洲', southAmerica:'南美洲', europe:'欧洲', asia:'亚洲', africa:'非洲', oceania:'大洋洲', other:'其他',
    language:'语言', chinese:'中文', english:'English',
    setupTitle:'项目设置', marketScan:'市场扫描', opportunityExplorer:'机会探索', tradeSuppliers:'贸易结构', ebayResearch:'eBay 研究', costMargin:'成本与利润', decisionCases:'决策案例', dataBackbone:'数据底座', dataSources:'数据源',
    searchCategories:'搜索分类', browseAll:'浏览全部分类', cachedReady:'分类缓存已就绪', taxonomySearchFirst:'分类', refreshTaxonomy:'刷新分类缓存',
    marketplace:'站点', categoryTaxonomy:'商品分类', comparableResearch:'可比商品研究', query:'搜索词', excludedTerms:'排除词', sort:'排序', pageSize:'每页数量', search:'搜索', allCategories:'全部分类', selectedCategory:'已选分类', categoryAttributes:'分类属性', required:'必填', optional:'可选', loadingAttributes:'正在加载属性…', openingCategory:'正在打开分类…', loadingTaxonomy:'正在读取分类缓存…', attachProject:'关联到项目', createProject:'创建项目', previous:'上一页', next:'下一页', title:'标题', condition:'成色', match:'匹配度', price:'价格', inputSample:'输入样本', retainedSample:'保留样本', retention:'保留率', medianPrice:'中位价', sandboxBlocked:'沙盒不可作为价格基准', verifiedMarketplace:'已验证市场数据', csvFile:'CSV 文件', uploadFilter:'上传并过滤', projectsEmpty:'暂无项目', productName:'商品名称', projectSearch:'搜索项目', checked:'已检查', yes:'是', environment:'环境', taxonomy:'分类体系', benchmark:'价格基准', provider:'数据源', refreshStatus:'刷新状态', oauthConnected:'OAuth 已连接', oauthTest:'测试 OAuth', runOauth:'运行 OAuth 测试', portfolioTitle:'产品组合', portfolioSubtitle:'', importSku:'导入 SKU 文件', chooseFile:'选择文件', importDrafts:'导入草稿', portfolioMatrix:'产品组合证据矩阵', portfolioBatches:'导入批次', noPortfolio:'暂无导入的产品组合', noMatrix:'暂无组合矩阵', downloadTemplate:'下载模板', batch:'批次', row:'第', created:'已创建', rejected:'已拒绝', pending:'待确认', notSelected:'未选择', evidence:'证据完整度', products:'商品', marketsLabel:'市场', bestMatch:'最佳匹配', priceLow:'价格从低到高', priceHigh:'价格从高到低', newlyListed:'最新上架', userUpload:'用户上传', available:'可用', inactive:'未启用', publicEndpoint:'公共接口', publicReference:'公共参考', localDatabase:'本地数据库', localPersistence:'本地持久化', historicalTariff:'历史关税参考', officialTariffLayer:'官方关税层', dataBackboneName:'数据底座', taxonomyBrowse:'分类体系 + 浏览接口', evidenceNarrative:'基于证据的分析结论', optionalApiKey:'可选 API Key',
  },
  en: {
    workspace:'Workspace', setup:'Project Setup', scan:'Market Scan', explorer:'Opportunity Explorer', trade:'Trade Structure', tariffSupply:'Tariff & Supply', ebay:'eBay Research', cost:'Cost & Margin', decision:'Decision Cases', portfolio:'Portfolio', backbone:'Data Backbone', sources:'Data Sources',
    newOpen:'New / open product', exportExcel:'Export Excel', noProject:'No active project', active:'active', draft:'draft', local:'Local',
    workspaceTitle:'Workspace', workspaceSub:'', projects:'Projects', filterProjects:'Filter projects',
    newAnalysis:'New analysis', whatProduct:'Product', chooseCategory:'Choose the closest product category', addAttributes:'Add key attributes', product:'Product', continue:'Continue', back:'Back', createAnalysis:'Create analysis', skipDetails:'Skip details', browseCategories:'Browse eBay categories', createDraft:'Create draft without category',
    targetMarkets:'Target markets', selected:'selected', searchCountry:'Search country or area', allRegions:'All regions', featured:'Featured markets', tradeOnly:'Trade research', fullSupport:'Full decision support', selectAllRegion:'Select region', clear:'Clear', globalMap:'Global market map', regionList:'Region list', mapHint:'',
    northAmerica:'North America', southAmerica:'South America', europe:'Europe', asia:'Asia', africa:'Africa', oceania:'Oceania', other:'Other',
    language:'Language', chinese:'中文', english:'English',
    setupTitle:'Project Setup', marketScan:'Market Scan', opportunityExplorer:'Opportunity Explorer', tradeSuppliers:'Trade Structure', ebayResearch:'eBay Research', costMargin:'Cost & Margin', decisionCases:'Decision Cases', dataBackbone:'Data Backbone', dataSources:'Data Sources',
    searchCategories:'Search categories', browseAll:'Browse all categories', cachedReady:'Taxonomy cache ready', taxonomySearchFirst:'Categories', refreshTaxonomy:'Refresh taxonomy cache',
    marketplace:'Marketplace', categoryTaxonomy:'Category taxonomy', comparableResearch:'Comparable research', query:'Query', excludedTerms:'Excluded terms', sort:'Sort', pageSize:'Page size', search:'Search', allCategories:'All categories', selectedCategory:'Selected category', categoryAttributes:'Category attributes', required:'Required', optional:'Optional', loadingAttributes:'Loading attributes…', openingCategory:'Opening category…', loadingTaxonomy:'Loading taxonomy cache…', attachProject:'Attach to project', createProject:'Create project', previous:'Previous', next:'Next', title:'Title', condition:'Condition', match:'Match', price:'Price', inputSample:'Input', retainedSample:'Retained', retention:'Retention', medianPrice:'Median', sandboxBlocked:'Blocked in Sandbox', verifiedMarketplace:'Verified marketplace observations', csvFile:'CSV file', uploadFilter:'Upload & filter', projectsEmpty:'No projects yet', productName:'Product name', projectSearch:'Search projects', checked:'Checked', yes:'Yes', environment:'Environment', taxonomy:'Taxonomy', benchmark:'Benchmark', provider:'Provider', refreshStatus:'Refresh status', oauthConnected:'OAuth connected', oauthTest:'Test OAuth', runOauth:'Run the OAuth test', portfolioTitle:'Portfolio', portfolioSubtitle:'', importSku:'Import SKU file', chooseFile:'Choose file', importDrafts:'Import drafts', portfolioMatrix:'Portfolio evidence matrix', portfolioBatches:'Portfolio batches', noPortfolio:'No imported portfolio', noMatrix:'No portfolio matrix yet', downloadTemplate:'Download template', batch:'Batch', row:'Row', created:'created', rejected:'rejected', pending:'Pending', notSelected:'Not selected', evidence:'Evidence', products:'Products', marketsLabel:'Markets', bestMatch:'Best match', priceLow:'Price low to high', priceHigh:'Price high to low', newlyListed:'Newly listed', userUpload:'User upload', available:'Available', inactive:'Not active', publicEndpoint:'Public endpoint', publicReference:'Public reference', localDatabase:'Local database', localPersistence:'Local persistence', historicalTariff:'Historical tariff reference', officialTariffLayer:'Official Tariff Layer', dataBackboneName:'Data Backbone', taxonomyBrowse:'Taxonomy + Browse', evidenceNarrative:'Evidence-only analysis narrative', optionalApiKey:'Optional API key',
  }
}

const Ctx=createContext(null)
export function I18nProvider({children}){
  const [locale,setLocale]=useState(()=>localStorage.getItem('bm_locale')||'zh')
  const value=useMemo(()=>({locale,setLocale:(v)=>{localStorage.setItem('bm_locale',v);setLocale(v)},t:(key,fallback)=>DICT[locale]?.[key] ?? DICT.en[key] ?? fallback ?? key}),[locale])
  return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}
export function useI18n(){ return useContext(Ctx) || {locale:'en',setLocale:()=>{},t:(k,f)=>f||k} }
